version: "3.2"
services:
  scheduler:
    build: ./scheduler
    volumes:
      - ImageIndexTrackerVolume:/data
  api:
    build: ./api
    volumes:
      - ImageIndexTrackerVolume:/data
    ports:
      - "8080:8080"
  nginx:
    build: ./nginx
    ports:
      - "80:80"

volumes:
  ImageIndexTrackerVolume:
    external: true