services:
  scheduler:
    build: ./scheduler
    volumes:
      - ./data:/data

  api:
    build: ./api
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
