services:
  scheduler:
    build: ./scheduler
    volumes:
      - '//c/Users/LucaAnholt/semantic_similarity_flas_api/data/:/data/'

  api:
    build: ./api
    volumes:
      - '//c/Users/LucaAnholt/semantic_similarity_flas_api/data/:/data/'
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
